version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.3.1
    container_name: elasticsearch-service
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    restart: always
    ports:
      - "9400:9200"
      - "9500:9300"
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml